<style>
.header {
margin-top:0px;
}
</style>
<div class="container">  <?php
      @ session_destroy() ;
      @ session_unregister("rid");
@session_unregister("ruser");
@session_unregister("rsex");
      ?>
 <p align="justify">ДОРОГІ користувачі!!! На цьому сайті Ви підберете собі гарну пару,
   друга по переписці, знайдете своє кохання  та зробите багато щє чого.
   Зареєстрованним користувачам доступні: </p>
    <ul  type="circle" align=left>
    <li>Додавання своєї анкети до бази</li>
    <li>Додавання до бази двох своїх фотографій </li>
    <li>Повна інформація по анкетам</li>
    <li>Вибір пари за ім`ям по чотирьом критеріям </li></ul>
   </td></tr></table> <!--Invitation end-->
   <!--Galary begin-->
  <table width=100%>
  <tr><th align=center colspan=4><span style="color:#00CCFF;">..::</span>НАШІ КРАЩІ<span style="color:#00CCFF;">::..</span></th></tr>
  <tr valign="top" align=center ><td>Руді</td><td>Біляві</td><td>Чорняві</td><td> Каштанові</td></tr>
  <tr align=center >
  <td valign="top"> <!--Red-->
<marquee style="display: block; height:200;width:150; behavior="scroll" direction="down" scrollamount="1" style="background-image: url(pic/Red_f_1.jpg); background-repeat: repeat-y">

 
 	
	<table border="0" cellspacing="0" cellpadding="0" style="margin: 0">
 			   <tr><td style="display:block; text-align:center; background:#ccc;"><IMG  src="pic/Red_m_1.jpg" align=top width=150 height=200>[ Владислав, 45 
			   </td></tr>
			   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Red_m_2.jpg" align=top  width=150 height=200>[ Мартін, 20 
	  	 	   </td></tr>
    		   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Red_f_1.jpg"align=top width=150 height=200>[ Глорія, 21
	  		   </td></tr>
	 			<tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Red_f_2.jpg"align=top width=150 height=200>[ Софія, 25 
	  		 	</td></tr>
			</table>
	  </marquee>
	  </td>
      <td valign="top"> <!--Blond-->
	    <marquee style="display: block; height: 200; width: 150;  behavior="scroll" direction="down" scrollamount="1"
		style="background-image: url(pic/Blo_f_1.jpg); background-repeat: repeat-y">
  		<table border="0" cellspacing="0" cellpadding="0" style="margin: 0">
 			   <tr><td style="display:block; text-align:center; background:#ccc;"><IMG  src="pic/Blo_m_1.jpg" align=top width=150 height=200>[ Арсен, 21 
			   </td></tr>
			   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Blo_m_2.jpg" align=top  width=150 height=200>[ Сергій, 23 
	  	 	   </td></tr>
    		   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Blo_f_1.jpg"align=top width=150 height=200>[ Інна, 20
	  		   </td></tr>
	 			<tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Blo_f_2.jpg"align=top width=150 height=200>[ Ангеліна, 22 
	  		 	</td></tr>
			</table>
	  </marquee>
	  </td>
      <td  valign="top"> <!--Black-->
	   <marquee style="display: block; height: 200; width: 150;  behavior="scroll" direction="down" scrollamount="1"
		style="background-image: url(pic/Cho_f_1.jpg); background-repeat: repeat-y">
  		<table border="0" cellspacing="0" cellpadding="0" style="margin: 0">
 			   <tr><td style="display:block; text-align:center; background:#ccc;"><IMG  src="pic/Cho_m_1.jpg" align=top width=150 height=200>[ Назар, 25 
			   </td></tr>
			   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Cho_m_2.jpg" align=top  width=150 height=200>[ Григорій, 19 
	  	 	   </td></tr>
    		   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Cho_f_1.jpg"align=top width=150 height=200>[ Марія, 21 
	  		   </td></tr>
	 			<tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Cho_f_2.jpg"align=top width=150 height=200>[ Вікторія, 19 
	  		 	</td></tr>
			</table>
	  </marquee>
	  </td>
      <td  valign="top"><!--Brown-->
	  <marquee style="display: block; height: 200; width: 150;  behavior="scroll" direction="down" scrollamount="1"
		style="background-image: url('pic/Kas_f_1.jpg'); background-repeat: repeat-y">
  		<table border="0" cellspacing="0" cellpadding="0" style="margin: 0">
 			   <tr><td style="display:block; text-align:center; background:#ccc;"><IMG  src="pic/Kas_m_1.jpg" align=top width=150 height=200>[ Гліб, 27 
			   </td></tr>
			   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Kas_m_2.jpg" align=top  width=150 height=200>[ Матвій, 22 
	  	 	   </td></tr>
    		   <tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Kas_f_1.jpg"align=top width=150 height=200>[ Наталія, 23 
	  		   </td></tr>
	 			<tr><td style="display:block; text-align:center;background:#ccc;"><IMG src="pic/Kas_f_2.jpg"align=top width=150 height=200>[ Олена, 28 
	  		 	</td></tr>
			</table>
	  </marquee>
</div>